name: weathering
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - pytorch-cuda=11.8
  - pytorch=2.6.0
  - torchvision=0.21.0
  - torchaudio=2.6.0
  - pip
  - pip:
    - diffusers==0.32.2
    - transformers==4.57.0
    - peft==0.14.0
    - accelerate==1.3.0
    - lpips==0.1.4
    - opencv-python==4.11.0.86
    - pillow==11.1.0
    - tqdm==4.66.4
    - qwen-vl-utils==0.0.14
    - scipy==1.15.3
    - numpy==2.2.6
    - protobuf==5.29.3
    - sentencepiece==0.2.0
